// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEMDlVZUAS15QZ7zCIG_xuFkOIpxMvZbM',
    appId: '1:359605877977:web:e3b2510228a5a9703152c8',
    messagingSenderId: '359605877977',
    projectId: 'chat-app-45147',
    authDomain: 'chat-app-45147.firebaseapp.com',
    storageBucket: 'chat-app-45147.appspot.com',
    measurementId: 'G-408QPN2DB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbNWfSnlKnIFstmksFULC3-27a2sFDKRs',
    appId: '1:359605877977:android:5a433a91d89369773152c8',
    messagingSenderId: '359605877977',
    projectId: 'chat-app-45147',
    storageBucket: 'chat-app-45147.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi95erwHKGm0PX57YQJzEDiKTkbw8MojI',
    appId: '1:359605877977:ios:0be9b1706eac9a263152c8',
    messagingSenderId: '359605877977',
    projectId: 'chat-app-45147',
    storageBucket: 'chat-app-45147.appspot.com',
    iosClientId: '359605877977-0p8garpss5rjb2nhq1oo4lge1jmadnaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi95erwHKGm0PX57YQJzEDiKTkbw8MojI',
    appId: '1:359605877977:ios:0be9b1706eac9a263152c8',
    messagingSenderId: '359605877977',
    projectId: 'chat-app-45147',
    storageBucket: 'chat-app-45147.appspot.com',
    iosClientId: '359605877977-0p8garpss5rjb2nhq1oo4lge1jmadnaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
